using ANcpLua.Analyzers.ExtensibleEnumMirror.Models;

namespace ANcpLua.Analyzers.ExtensibleEnumMirror.Generation;

internal static class MirrorOutputGenerator
{
    private const string Tool = "ANcpLua.Analyzers.ExtensibleEnumMirror";
    private const string UnknownMember = "Unknown";

    public static FileWithName Generate(MirrorModel model)
    {
        var sb = new IndentedStringBuilder();
        sb.Append(GeneratedCodeHelpers.AutoGeneratedHeader(Tool));
        sb.AppendLine(GeneratedCodeHelpers.NullableEnable);
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.MarkerNamespace))
        {
            sb.AppendLine($"namespace {model.MarkerNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial {model.MarkerKeyword} {model.MarkerName}");
        using (sb.BeginBlock())
        {
            EmitEnum(sb, model);
            sb.AppendLine();
            EmitToKind(sb, model);
            sb.AppendLine();
            EmitToStruct(sb, model);
            sb.AppendLine();
            EmitKnownValues(sb, model);
        }

        return new FileWithName(GetHintName(model), sb.ToString());
    }

    private static void EmitEnum(IndentedStringBuilder sb, MirrorModel model)
    {
        sb.AppendLine("/// <summary>CLR enum mirror of the extensible-enum struct's known static values.</summary>");
        sb.AppendLine("public enum Kind");
        using (sb.BeginBlock())
        {
            sb.AppendLine($"{UnknownMember} = 0,");
            for (var i = 0; i < model.KnownMembers.Length; i++)
                sb.AppendLine($"{model.KnownMembers[i]} = {i + 1},");
        }
    }

    private static void EmitToKind(IndentedStringBuilder sb, MirrorModel model)
    {
        sb.AppendLine($"/// <summary>Maps a {model.TargetSimpleName} value to its <see cref=\"Kind\"/>.</summary>");
        sb.AppendLine($"public static Kind ToKind({model.TargetFullyQualified} value)");
        using (sb.BeginBlock())
        {
            foreach (var name in model.KnownMembers)
                sb.AppendLine($"if (value == {model.TargetFullyQualified}.{name}) return Kind.{name};");
            sb.AppendLine($"return Kind.{UnknownMember};");
        }
    }

    private static void EmitToStruct(IndentedStringBuilder sb, MirrorModel model)
    {
        sb.AppendLine($"/// <summary>Maps a <see cref=\"Kind\"/> back to its {model.TargetSimpleName} value. Returns <c>default</c> for <see cref=\"Kind.{UnknownMember}\"/>.</summary>");
        sb.AppendLine($"public static {model.TargetFullyQualified} ToStruct(Kind kind)");
        using (sb.BeginBlock())
        {
            foreach (var name in model.KnownMembers)
                sb.AppendLine($"if (kind == Kind.{name}) return {model.TargetFullyQualified}.{name};");
            sb.AppendLine("return default;");
        }
    }

    private static void EmitKnownValues(IndentedStringBuilder sb, MirrorModel model)
    {
        var values = model.KnownMembers.Length is 0
            ? string.Empty
            : string.Join(", ", model.KnownMembers.Select(n => $"{model.TargetFullyQualified}.{n}"));

        sb.AppendLine($"/// <summary>All public static known values of {model.TargetSimpleName}, in alphabetical declaration order.</summary>");
        sb.AppendLine($"public static global::System.Collections.Generic.IReadOnlyList<{model.TargetFullyQualified}> KnownValues {{ get; }} = new {model.TargetFullyQualified}[] {{ {values} }};");
    }

    private static string GetHintName(MirrorModel model) =>
        string.IsNullOrEmpty(model.MarkerNamespace)
            ? $"{model.MarkerName}.ExtensibleEnumMirror.g.cs"
            : $"{model.MarkerNamespace}.{model.MarkerName}.ExtensibleEnumMirror.g.cs";
}
