// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET11_0_OR_GREATER

namespace System.Runtime.CompilerServices;

/// <summary>
///     Backport of <see cref="IUnion" /> for .NET 10 and earlier, required by C# 15 <c>union</c> declarations.
/// </summary>
internal interface IUnion
{
    /// <summary>The value of the case the union currently holds.</summary>
    object? Value { get; }
}

#endif
