// <auto-generated />
#nullable enable

#if !NET9_0_OR_GREATER

namespace System.Runtime.CompilerServices;

using System.Diagnostics.CodeAnalysis;

/// <summary>
///     Backport of <see cref="ParamCollectionAttribute"/> for .NET 8 and earlier.
/// </summary>
[AttributeUsage(AttributeTargets.Parameter)]
[ExcludeFromCodeCoverage]
internal sealed class ParamCollectionAttribute : Attribute
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ParamCollectionAttribute"/> class.
    /// </summary>
    public ParamCollectionAttribute()
    {
    }
}

#endif
