// <auto-generated />
#nullable enable

#if !NET7_0_OR_GREATER

namespace System.Runtime.CompilerServices;

using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

/// <summary>Specifies that a type has required members or that a member is required.</summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property,
    Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
[ExcludeFromCodeCoverage]
internal sealed class RequiredMemberAttribute : Attribute;

#endif
