// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET11_0_OR_GREATER

using System.Diagnostics.CodeAnalysis;

namespace System.Runtime.CompilerServices;

/// <summary>
///     Backport of <see cref="UnionAttribute" /> for .NET 10 and earlier, required by C# 15 <c>union</c> declarations.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[ExcludeFromCodeCoverage]
internal sealed class UnionAttribute : Attribute
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="UnionAttribute" /> class.
    /// </summary>
    public UnionAttribute()
    {
    }
}

#endif
