// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />
#nullable enable

#if !NET6_0_OR_GREATER

namespace System.Diagnostics;

using System.Diagnostics.CodeAnalysis;

/// <summary>
///     Types and methods attributed with StackTraceHidden will be omitted from the stack trace text.
/// </summary>
[AttributeUsage(
    AttributeTargets.Class | AttributeTargets.Method | AttributeTargets.Constructor | AttributeTargets.Struct,
    Inherited = false)]
[ExcludeFromCodeCoverage]
internal sealed class StackTraceHiddenAttribute : Attribute
{
}

#endif
