using ANcpLua.Analyzers.ExtensibleEnumMirror.Extraction;
using ANcpLua.Analyzers.ExtensibleEnumMirror.Generation;

namespace ANcpLua.Analyzers.ExtensibleEnumMirror;

/// <summary>
///     Mirrors TypeSpec <c>[CodeGenType]</c> string-backed extensible-enum structs (the canonical
///     pattern in <c>OpenAI</c>, <c>Anthropic.SDK</c>, <c>Microsoft.Agents.AI</c>, and any other
///     <c>System.ClientModel</c>-based SDK) as a real CLR <c>enum</c> plus
///     <c>ToKind</c> / <c>ToStruct</c> / <c>KnownValues</c> helpers, so consumers can switch over
///     them in modern <c>switch</c> expressions without falling back to <c>var x when x == ...</c>
///     guard arms or magic strings.
/// </summary>
/// <remarks>
///     <para>
///         Usage: declare an empty <c>partial class</c> marker and apply
///         <c>[ExtensibleEnumMirror(typeof(Target))]</c>. The generator emits the <c>Kind</c> enum
///         and helpers into the marker's partial body. The marker attribute is emitted via
///         <see cref="IncrementalGeneratorPostInitializationContext.AddSource(string, string)" />
///         so consumers do not need a separate attribute package.
///     </para>
/// </remarks>
[Generator]
public sealed class ExtensibleEnumMirrorGenerator : IIncrementalGenerator
{
    internal const string AttributeNamespace = "ANcpLua.Analyzers.ExtensibleEnumMirror";
    internal const string AttributeShortName = "ExtensibleEnumMirrorAttribute";
    internal const string AttributeFullName = AttributeNamespace + "." + AttributeShortName;

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace ANcpLua.Analyzers.ExtensibleEnumMirror;

        /// <summary>
        /// Marks a partial class or struct as the host of a generated CLR enum mirror for the
        /// TypeSpec extensible-enum struct identified by <paramref name="targetType"/>.
        /// </summary>
        /// <remarks>
        /// The decorated type must be <c>partial</c>. The target type must be a non-generic
        /// <c>readonly struct</c> implementing <c>IEquatable&lt;Self&gt;</c> with public static
        /// get-only properties of itself (the canonical TypeSpec <c>[CodeGenType]</c> shape).
        /// </remarks>
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
            AllowMultiple = false,
            Inherited = false)]
        [global::System.Diagnostics.Conditional("ANCPLUA_EXTENSIBLE_ENUM_MIRROR_USAGES")]
        internal sealed class ExtensibleEnumMirrorAttribute : global::System.Attribute
        {
            public ExtensibleEnumMirrorAttribute(global::System.Type targetType)
            {
                TargetType = targetType;
            }

            public global::System.Type TargetType { get; }
        }

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ExtensibleEnumMirrorAttribute.g.cs", AttributeSource));

        var flows = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
            static (ctx, ct) => MirrorExtractor.Extract(ctx, ct));

        var models = flows.ReportAndStop(context);

        var files = models
            .Select(static (model, _) => MirrorOutputGenerator.Generate(model))
            .CollectAsEquatableArray();

        files.AddSources(context);
    }
}
