// <auto-generated />
#nullable enable

#if !NET7_0_OR_GREATER

namespace System.Diagnostics.CodeAnalysis;

using System.ComponentModel;

/// <summary>
///     Specifies that the constructor sets all required members for the current type,
///     and callers do not need to set any required members themselves.
/// </summary>
[AttributeUsage(AttributeTargets.Constructor, Inherited = false)]
[EditorBrowsable(EditorBrowsableState.Never)]
[ExcludeFromCodeCoverage]
internal sealed class SetsRequiredMembersAttribute : Attribute
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="SetsRequiredMembersAttribute"/> class.
    /// </summary>
    public SetsRequiredMembersAttribute()
    {
    }
}

#endif
