using ANcpLua.Analyzers.DiscriminatedUnion.Models;

namespace ANcpLua.Analyzers.DiscriminatedUnion.Generation;

internal static class UnionOutputGenerator
{
    private const string Tool = "ANcpLua.Analyzers.DiscriminatedUnion";

    public static FileWithName Generate(UnionModel model)
    {
        var sb = new IndentedStringBuilder();
        sb.Append(GeneratedCodeHelpers.AutoGeneratedHeader(Tool));
        sb.AppendLine(GeneratedCodeHelpers.NullableEnable);
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.RootNamespace))
        {
            sb.AppendLine($"namespace {model.RootNamespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"abstract partial record {model.RootName}{model.TypeParameterList}");
        using (sb.BeginBlock())
        {
            sb.AppendLine($"private {model.RootName}() {{ }}");
            sb.AppendLine();
            EmitMatchSignature(sb, model, abstractKeyword: true);
            sb.AppendLine();
            EmitSwitchSignature(sb, model, abstractKeyword: true);
            sb.AppendLine();

            for (var i = 0; i < model.Cases.Length; i++)
            {
                EmitCase(sb, model, model.Cases[i]);
                if (i < model.Cases.Length - 1)
                    sb.AppendLine();
            }
        }

        return new FileWithName(GetHintName(model), sb.ToString());
    }

    private static void EmitMatchSignature(IndentedStringBuilder sb, UnionModel model, bool abstractKeyword)
    {
        sb.AppendLine("/// <summary>Exhaustively dispatches on the union case, returning a value.</summary>");
        var prefix = abstractKeyword ? "public abstract" : "public override";
        sb.AppendLine($"{prefix} TResult Match<TResult>(");
        WriteFuncParameters(sb, model);
        sb.AppendLine(abstractKeyword ? ");" : ");  // overridden per case");
    }

    private static void EmitSwitchSignature(IndentedStringBuilder sb, UnionModel model, bool abstractKeyword)
    {
        sb.AppendLine("/// <summary>Exhaustively dispatches on the union case for side effects.</summary>");
        var prefix = abstractKeyword ? "public abstract" : "public override";
        sb.AppendLine($"{prefix} void Switch(");
        WriteActionParameters(sb, model);
        sb.AppendLine(abstractKeyword ? ");" : ");  // overridden per case");
    }

    private static void EmitCase(IndentedStringBuilder sb, UnionModel model, UnionCase @case)
    {
        sb.AppendLine($"public sealed partial record {@case.Name} : {model.RootName}{model.TypeParameterList}");
        using (sb.BeginBlock())
        {
            sb.AppendLine("/// <inheritdoc />");
            sb.AppendLine("public override TResult Match<TResult>(");
            WriteFuncParameters(sb, model);
            sb.AppendLine($") => {@case.ParameterName}(this);");
            sb.AppendLine();
            sb.AppendLine("/// <inheritdoc />");
            sb.AppendLine("public override void Switch(");
            WriteActionParameters(sb, model);
            sb.AppendLine($") => {@case.ParameterName}(this);");
        }
    }

    private static void WriteFuncParameters(IndentedStringBuilder sb, UnionModel model)
    {
        // BeginBlock(opener: null) only increments indent. We deliberately don't use a `using`
        // here — the IndentScope is a struct with no finalizer, so discarding it skips the
        // automatic `}` emission. EndBlock(closer: null) just decrements indent again.
        sb.BeginBlock(opener: null);
        for (var i = 0; i < model.Cases.Length; i++)
        {
            var c = model.Cases[i];
            var sep = i < model.Cases.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"global::System.Func<{c.Name}, TResult> {c.ParameterName}{sep}");
        }
        sb.EndBlock(closer: null);
    }

    private static void WriteActionParameters(IndentedStringBuilder sb, UnionModel model)
    {
        sb.BeginBlock(opener: null);
        for (var i = 0; i < model.Cases.Length; i++)
        {
            var c = model.Cases[i];
            var sep = i < model.Cases.Length - 1 ? "," : string.Empty;
            sb.AppendLine($"global::System.Action<{c.Name}> {c.ParameterName}{sep}");
        }
        sb.EndBlock(closer: null);
    }

    private static string GetHintName(UnionModel model) =>
        string.IsNullOrEmpty(model.RootNamespace)
            ? $"{model.RootName}.DiscriminatedUnion.g.cs"
            : $"{model.RootNamespace}.{model.RootName}.DiscriminatedUnion.g.cs";
}
