// <auto-generated />
#nullable enable

namespace ANcpLua.Roslyn.Utilities.Comparers;

using System;
using System.Collections.Generic;

/// <summary>
///     A singleton ordinal string comparer implementing both <see cref="IComparer{T}"/>
///     and <see cref="IEqualityComparer{T}"/> for consistent, allocation-free comparisons.
/// </summary>
/// <remarks>
///     Ordinal comparison performs a byte-by-byte comparison of the string's UTF-16 code units,
///     making it case-sensitive and culture-insensitive. This is the fastest string comparison
///     method and is ideal for internal identifiers, file paths, and dictionary keys.
/// </remarks>
#if ANCPLUA_ROSLYN_PUBLIC
public
#else
internal
#endif
sealed class StringOrdinalComparer : IComparer<string>, IEqualityComparer<string>
{
    /// <summary>
    ///     Gets the singleton instance of <see cref="StringOrdinalComparer"/>.
    /// </summary>
    public static readonly StringOrdinalComparer Instance = new();

    private StringOrdinalComparer()
    {
    }

    /// <inheritdoc />
    public int Compare(string? x, string? y)
    {
        return StringComparer.Ordinal.Compare(x, y);
    }

    /// <inheritdoc />
    public bool Equals(string? x, string? y)
    {
        return StringComparer.Ordinal.Equals(x, y);
    }

    /// <inheritdoc />
    public int GetHashCode(string obj)
    {
        return StringComparer.Ordinal.GetHashCode(obj);
    }
}

/// <summary>
///     A singleton ordinal case-insensitive string comparer implementing both <see cref="IComparer{T}"/>
///     and <see cref="IEqualityComparer{T}"/> for consistent, allocation-free comparisons.
/// </summary>
/// <remarks>
///     Ordinal case-insensitive comparison performs case-folding using the invariant culture's
///     uppercase mapping before comparing. This is suitable for case-insensitive identifiers
///     and file paths on case-insensitive file systems (e.g., Windows).
/// </remarks>
#if ANCPLUA_ROSLYN_PUBLIC
public
#else
internal
#endif
sealed class StringOrdinalIgnoreCaseComparer : IComparer<string>, IEqualityComparer<string>
{
    /// <summary>
    ///     Gets the singleton instance of <see cref="StringOrdinalIgnoreCaseComparer"/>.
    /// </summary>
    public static readonly StringOrdinalIgnoreCaseComparer Instance = new();

    private StringOrdinalIgnoreCaseComparer()
    {
    }

    /// <inheritdoc />
    public int Compare(string? x, string? y)
    {
        return StringComparer.OrdinalIgnoreCase.Compare(x, y);
    }

    /// <inheritdoc />
    public bool Equals(string? x, string? y)
    {
        return StringComparer.OrdinalIgnoreCase.Equals(x, y);
    }

    /// <inheritdoc />
    public int GetHashCode(string obj)
    {
        return StringComparer.OrdinalIgnoreCase.GetHashCode(obj);
    }
}
