// Copyright (c) Microsoft. All rights reserved.

using AwesomeAssertions;
using AwesomeAssertions.Execution;
using AwesomeAssertions.Primitives;
using Microsoft.CodeAnalysis;

namespace ANcpLua.Roslyn.Utilities.Testing.Workflows.Assertions;

/// <summary>
/// AwesomeAssertions extensions for SyntaxTree generated by ExecutorRouteGenerator.
/// Lets tests do: tree.Should().AddHandler&lt;TIn,TOut&gt;("Foo").And.RegisterSentMessageType&lt;TMsg&gt;().And.HaveHierarchy("Outer","Inner").
/// </summary>
internal sealed class SyntaxTreeAssertions : ObjectAssertions<SyntaxTree, SyntaxTreeAssertions>
{
    private readonly string _syntaxString;

    public SyntaxTreeAssertions(SyntaxTree instance, AssertionChain assertionChain) : base(instance, assertionChain)
    {
        this._syntaxString = instance.ToString();
    }

    public AndConstraint<SyntaxTreeAssertions> AddHandler(string handlerName) =>
        this.Contains($".AddHandler({handlerName})", $"expected handler {handlerName} to be registered");

    public AndConstraint<SyntaxTreeAssertions> AddHandler(string handlerName, string inTypeParam) =>
        this.Contains($".AddHandler<{inTypeParam}>({handlerName})", $"expected handler {handlerName} to be registered");

    public AndConstraint<SyntaxTreeAssertions> AddHandler(string handlerName, string inTypeParam, string outTypeParam) =>
        this.Contains($".AddHandler<{inTypeParam},{outTypeParam}>({handlerName})", $"expected handler {handlerName} to be registered");

    public AndConstraint<SyntaxTreeAssertions> AddHandler<TIn>(string handlerName, bool globalQualified = false)
    {
        Type inType = typeof(TIn);
        string inTypeParam = globalQualified ? $"global::{inType.FullName}" : inType.Name;
        return this.AddHandler(handlerName, inTypeParam);
    }

    public AndConstraint<SyntaxTreeAssertions> AddHandler<TIn, TOut>(string handlerName, bool globalQualified = false)
    {
        Type inType = typeof(TIn), outType = typeof(TOut);
        string inTypeParam = globalQualified ? $"global::{inType.FullName}" : inType.Name;
        string outTypeParam = globalQualified ? $"global::{outType.FullName}" : outType.Name;
        return this.AddHandler(handlerName, inTypeParam, outTypeParam);
    }

    public AndConstraint<SyntaxTreeAssertions> HaveNoHandlers() =>
        this.NotContain(".AddHandler(", "expected no handlers to be registered");

    public AndConstraint<SyntaxTreeAssertions> RegisterSentMessageType(string messageTypeParam) =>
        this.Contains($".SendsMessage<{messageTypeParam}>()", $"expected message type {messageTypeParam} to be registered");

    public AndConstraint<SyntaxTreeAssertions> RegisterSentMessageType<TMessage>(bool globalQualified = true)
    {
        Type messageType = typeof(TMessage);
        string messageTypeParam = globalQualified ? $"global::{messageType.FullName}" : messageType.Name;
        return this.RegisterSentMessageType(messageTypeParam);
    }

    public AndConstraint<SyntaxTreeAssertions> NotRegisterSentMessageTypes() =>
        this.NotContain(".SendsMessage<", "expected no message types to be registered");

    public AndConstraint<SyntaxTreeAssertions> RegisterYieldedOutputType(string outputTypeParam) =>
        this.Contains($".YieldsOutput<{outputTypeParam}>()", $"expected output type {outputTypeParam} to be registered");

    public AndConstraint<SyntaxTreeAssertions> RegisterYieldedOutputType<TOutput>(bool globalQualified = true)
    {
        Type outputType = typeof(TOutput);
        string outputTypeParam = globalQualified ? $"global::{outputType.FullName}" : outputType.Name;
        return this.RegisterYieldedOutputType(outputTypeParam);
    }

    public AndConstraint<SyntaxTreeAssertions> NotRegisterYieldedOutputTypes() =>
        this.NotContain(".YieldsOutput<", "expected no output types to be registered");

    public AndConstraint<SyntaxTreeAssertions> HaveNamespace() =>
        this.Contains("namespace ", "expected namespace declaration");

    public AndConstraint<SyntaxTreeAssertions> NotHaveNamespace() =>
        this.NotContain("namespace ", "expected no namespace declaration");

    public AndConstraint<SyntaxTreeAssertions> HaveHierarchy(params string[] expectedNesting)
    {
        if (expectedNesting.Length == 0)
        {
            return new AndConstraint<SyntaxTreeAssertions>(this);
        }

        int[] indicies = new int[expectedNesting.Length];
        for (int i = 0; i < expectedNesting.Length; i++)
        {
            indicies[i] = this._syntaxString.IndexOf($"partial class {expectedNesting[i]}", StringComparison.Ordinal);
        }

        AndConstraint<SyntaxTreeAssertions> running = this.ContainPartialDeclaration(0, indicies[0], expectedNesting[0]);
        for (int i = 1; i < expectedNesting.Length; i++)
        {
            running = running.And.ContainPartialDeclaration(i, indicies[i], expectedNesting[i])
                            .And.DeclarePartialsInCorrectOrder(indicies[i - 1], indicies[i], expectedNesting[i - 1], expectedNesting[i]);
        }

        return running;
    }

    private AndConstraint<SyntaxTreeAssertions> Contains(string needle, string because)
    {
        this.CurrentAssertionChain
            .ForCondition(this._syntaxString.Contains(needle))
            .BecauseOf(because)
            .FailWith("Expected {context} to contain {0}{reason}, but it was not found. Actual syntax: {1}", needle, this._syntaxString);
        return new(this);
    }

    private AndConstraint<SyntaxTreeAssertions> NotContain(string needle, string because)
    {
        this.CurrentAssertionChain
            .ForCondition(!this._syntaxString.Contains(needle))
            .BecauseOf(because)
            .FailWith("Expected {context} to not contain {0}{reason}, but it was found. Actual syntax: {1}", needle, this._syntaxString);
        return new(this);
    }

    private AndConstraint<SyntaxTreeAssertions> ContainPartialDeclaration(int level, int index, string className)
    {
        this.CurrentAssertionChain
            .ForCondition(index > 0)
            .BecauseOf($"expected \"partial class {className}\" at nesting level {level}")
            .FailWith("Expected {context} to contain \"partial class {0}\" at nesting level {1}{reason}, but it was not found. Actual syntax: {2}",
                className, level, this._syntaxString);
        return new(this);
    }

    private AndConstraint<SyntaxTreeAssertions> DeclarePartialsInCorrectOrder(int prevIndex, int currIndex, string prevClass, string currClass)
    {
        this.CurrentAssertionChain
            .ForCondition(prevIndex < currIndex)
            .BecauseOf($"expected \"partial class {prevClass}\" before \"partial class {currClass}\"")
            .FailWith("Expected {context} to have \"partial class {0}\" before \"partial class {1}\"{reason}. Actual syntax: {2}",
                prevClass, currClass, this._syntaxString);
        return new(this);
    }
}

internal static class SyntaxTreeFluentExtensions
{
    public static SyntaxTreeAssertions Should(this SyntaxTree syntaxTree) => new(syntaxTree, AssertionChain.GetOrCreate());
}
