namespace ANcpLua.Roslyn.Utilities;

#if ANCPLUA_ROSLYN_PUBLIC
public
#else
internal
#endif
static class GeneratedCodeHelpers
{
    public static string NullableEnable => "#nullable enable";
    public static string NullableDisable => "#nullable disable";
    public static string NullableRestore => "#nullable restore";

    public static string GeneratedCodeAttribute(string toolName, string? version = null) =>
        version is null
            ? $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{toolName}\", null)]"
            : $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{toolName}\", \"{version}\")]";

    public static string EditorBrowsableNever =>
        "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

    public static string ExcludeFromCodeCoverage =>
        "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]";

    public static string DebuggerNonUserCode =>
        "[global::System.Diagnostics.DebuggerNonUserCode]";

    public static string CompilerGenerated =>
        "[global::System.Runtime.CompilerServices.CompilerGenerated]";

    public static string AutoGeneratedHeader(string toolName) => $"""
        // <auto-generated/>
        // This file was auto-generated by {toolName}.
        // Do not modify this file directly.

        """;

    public static string AutoGeneratedHeaderWithTimestamp(string toolName, DateTimeOffset timestamp) => $"""
        // <auto-generated/>
        // This file was auto-generated by {toolName} at {timestamp:O}.
        // Do not modify this file directly.

        """;

    public static string SuppressWarnings(params string[] warningIds)
    {
        if (warningIds.Length == 0)
            return string.Empty;
        return $"#pragma warning disable {string.Join(", ", warningIds)}";
    }

    public static string RestoreWarnings(params string[] warningIds)
    {
        if (warningIds.Length == 0)
            return string.Empty;
        return $"#pragma warning restore {string.Join(", ", warningIds)}";
    }
}

#if ANCPLUA_ROSLYN_PUBLIC
public
#else
internal
#endif
sealed class IndentedStringBuilder
{
    private readonly StringBuilder _sb;
    private readonly string _indentString;
    private int _indentLevel;
    private bool _needsIndent;

    public IndentedStringBuilder(int initialCapacity = 256, string indentString = "    ")
    {
        _sb = new StringBuilder(initialCapacity);
        _indentString = indentString;
        _needsIndent = true;
    }

    public int Length => _sb.Length;

    public IndentedStringBuilder Append(string text)
    {
        WriteIndentIfNeeded();
        _sb.Append(text);
        return this;
    }

    public IndentedStringBuilder Append(char c)
    {
        WriteIndentIfNeeded();
        _sb.Append(c);
        return this;
    }

    public IndentedStringBuilder AppendLine()
    {
        _sb.AppendLine();
        _needsIndent = true;
        return this;
    }

    public IndentedStringBuilder AppendLine(string text)
    {
        WriteIndentIfNeeded();
        _sb.AppendLine(text);
        _needsIndent = true;
        return this;
    }

    public IndentedStringBuilder AppendLineNoIndent(string text)
    {
        _sb.AppendLine(text);
        _needsIndent = true;
        return this;
    }

    public IndentedStringBuilder Indent()
    {
        _indentLevel++;
        return this;
    }

    public IndentedStringBuilder Outdent()
    {
        if (_indentLevel > 0)
            _indentLevel--;
        return this;
    }

    public IndentScope BeginBlock(string? opener = "{")
    {
        if (opener is not null)
            AppendLine(opener);
        Indent();
        return new IndentScope(this);
    }

    public IndentScope BeginNamespace(string namespaceName)
    {
        AppendLine($"namespace {namespaceName}");
        return BeginBlock();
    }

    public IndentScope BeginClass(string modifiers, string className, string? baseType = null)
    {
        var declaration = baseType is null
            ? $"{modifiers} class {className}"
            : $"{modifiers} class {className} : {baseType}";
        AppendLine(declaration);
        return BeginBlock();
    }

    public IndentScope BeginMethod(string modifiers, string returnType, string methodName, string parameters = "")
    {
        AppendLine($"{modifiers} {returnType} {methodName}({parameters})");
        return BeginBlock();
    }

    public IndentScope BeginIf(string condition)
    {
        AppendLine($"if ({condition})");
        return BeginBlock();
    }

    public IndentScope BeginElse()
    {
        AppendLine("else");
        return BeginBlock();
    }

    public IndentScope BeginForEach(string variableType, string variableName, string collection)
    {
        AppendLine($"foreach ({variableType} {variableName} in {collection})");
        return BeginBlock();
    }

    public void EndBlock(string? closer = "}")
    {
        Outdent();
        if (closer is not null)
            AppendLine(closer);
    }

    public override string ToString() => _sb.ToString();

    public void Clear()
    {
        _sb.Clear();
        _indentLevel = 0;
        _needsIndent = true;
    }

    private void WriteIndentIfNeeded()
    {
        if (!_needsIndent)
            return;

        for (var i = 0; i < _indentLevel; i++)
            _sb.Append(_indentString);

        _needsIndent = false;
    }
}

#if ANCPLUA_ROSLYN_PUBLIC
public
#else
internal
#endif
readonly struct IndentScope : IDisposable
{
    private readonly IndentedStringBuilder _builder;

    public IndentScope(IndentedStringBuilder builder)
    {
        _builder = builder;
    }

    public void Dispose()
    {
        _builder.EndBlock();
    }
}
