using ANcpLua.Roslyn.Utilities.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ANcpLua.Roslyn.Utilities;

/// <summary>
///     Extension methods for <see cref="SourceProductionContext" />.
/// </summary>
public static class SourceProductionContextExtensions
{
    /// <summary>
    ///     Adds source code with a standardized header.
    /// </summary>
    public static void AddSourceWithHeader(
        this SourceProductionContext context,
        string hintName,
        string sourceCode,
        string? generatorName = null)
    {
        var header = GenerateHeader(generatorName ?? "ANcpLua.SourceGen");
        var fullSource = header + sourceCode;
        context.AddSource(hintName, SourceText.From(fullSource, Encoding.UTF8));
    }

    /// <summary>
    ///     Adds source code from a StringBuilder with a standardized header.
    /// </summary>
    public static void AddSourceWithHeader(
        this SourceProductionContext context,
        string hintName,
        StringBuilder sourceBuilder,
        string? generatorName = null)
    {
        context.AddSourceWithHeader(hintName, sourceBuilder.ToString(), generatorName);
    }

    /// <summary>
    ///     Reports a diagnostic from a <see cref="DiagnosticInfo" />.
    /// </summary>
    public static void ReportDiagnostic(this SourceProductionContext context, DiagnosticInfo diagnosticInfo)
    {
        context.ReportDiagnostic(diagnosticInfo.ToDiagnostic());
    }

    /// <summary>
    ///     Generates a diagnostic for the selected exception.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="id">The diagnostic ID.</param>
    /// <param name="exception">The exception to report.</param>
    /// <param name="prefix">Optional prefix for the diagnostic ID.</param>
    /// <exception cref="ArgumentNullException">Thrown when id or exception is null.</exception>
    public static void ReportException(
        this SourceProductionContext context,
        string id,
        Exception exception,
        string? prefix = null)
    {
        id = id ?? throw new ArgumentNullException(nameof(id));
        exception = exception ?? throw new ArgumentNullException(nameof(exception));

        context.ReportDiagnostic(exception.ToDiagnostic(id, prefix));
    }

    /// <summary>
    ///     Creates a diagnostic for the selected exception.
    /// </summary>
    /// <param name="exception">The exception to convert.</param>
    /// <param name="id">The diagnostic ID.</param>
    /// <param name="prefix">Optional prefix for the diagnostic ID.</param>
    /// <exception cref="ArgumentNullException">Thrown when exception or id is null.</exception>
    public static Diagnostic ToDiagnostic(
        this Exception exception,
        string id,
        string? prefix = null)
    {
        exception = exception ?? throw new ArgumentNullException(nameof(exception));
        id = id ?? throw new ArgumentNullException(nameof(id));

        if (prefix is not null) id = $"{prefix}{id}";

        return Diagnostic.Create(
            new DiagnosticDescriptor(
                id,
                "Exception: ",
                $"{exception}",
                "Usage",
                DiagnosticSeverity.Error,
                true),
            Location.None);
    }

    private static string GenerateHeader(string generatorName)
    {
        return $"""
                // <auto-generated/>
                // Generated by {generatorName}
                #nullable enable

                """;
    }
}