// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// <auto-generated />

#nullable enable

#if !NET6_0_OR_GREATER

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace System.Linq;

/// <summary>
///     Backport of the <see cref="Enumerable" /> operators that .NET Standard 2.0 lacks:
///     <c>DistinctBy</c> (.NET 6) and <c>SkipLast</c> / <c>TakeLast</c> (.NET Core 2.0, .NET Standard 2.1).
///     Compiled only where the framework does not ship them, so modern targets bind to <see cref="Enumerable" />
///     without CS0121 ambiguity.
/// </summary>
[ExcludeFromCodeCoverage]
internal static class EnumerablePolyfills
{
    /// <summary>Returns distinct elements from a sequence according to a key selector.</summary>
    public static IEnumerable<TSource> DistinctBy<TSource, TKey>(
        this IEnumerable<TSource> source,
        Func<TSource, TKey> keySelector) =>
        DistinctBy(source, keySelector, null);

    /// <summary>Returns distinct elements from a sequence according to a key selector and key comparer.</summary>
    public static IEnumerable<TSource> DistinctBy<TSource, TKey>(
        this IEnumerable<TSource> source,
        Func<TSource, TKey> keySelector,
        IEqualityComparer<TKey>? comparer)
    {
        if (source is null) throw new ArgumentNullException(nameof(source));
        if (keySelector is null) throw new ArgumentNullException(nameof(keySelector));

        return Iterator(source, keySelector, comparer);

        static IEnumerable<TSource> Iterator(
            IEnumerable<TSource> source,
            Func<TSource, TKey> keySelector,
            IEqualityComparer<TKey>? comparer)
        {
            var seen = new HashSet<TKey>(comparer);
            foreach (var item in source)
                if (seen.Add(keySelector(item)))
                    yield return item;
        }
    }

#if !NETCOREAPP2_0_OR_GREATER && !NETSTANDARD2_1_OR_GREATER
    /// <summary>Returns all elements except the last <paramref name="count" />; all of them when <paramref name="count" /> is not positive.</summary>
    public static IEnumerable<TSource> SkipLast<TSource>(this IEnumerable<TSource> source, int count)
    {
        if (source is null) throw new ArgumentNullException(nameof(source));

        return count <= 0 ? source.Skip(0) : Iterator(source, count);

        static IEnumerable<TSource> Iterator(IEnumerable<TSource> source, int count)
        {
            var queue = new Queue<TSource>();
            foreach (var item in source)
            {
                if (queue.Count == count)
                    yield return queue.Dequeue();
                queue.Enqueue(item);
            }
        }
    }

    /// <summary>Returns the last <paramref name="count" /> elements; none when <paramref name="count" /> is not positive.</summary>
    public static IEnumerable<TSource> TakeLast<TSource>(this IEnumerable<TSource> source, int count)
    {
        if (source is null) throw new ArgumentNullException(nameof(source));

        return count <= 0 ? Enumerable.Empty<TSource>() : Iterator(source, count);

        static IEnumerable<TSource> Iterator(IEnumerable<TSource> source, int count)
        {
            var queue = new Queue<TSource>();
            foreach (var item in source)
            {
                if (queue.Count == count)
                    queue.Dequeue();
                queue.Enqueue(item);
            }

            foreach (var item in queue)
                yield return item;
        }
    }
#endif
}

#endif
