// <auto-generated />
#nullable enable

#if !NET8_0_OR_GREATER

namespace System;

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Provides an abstraction for time, allowing for easier testing and mocking of time-dependent code.
/// </summary>
/// <remarks>
/// This is a polyfill for System.TimeProvider which was introduced in .NET 8.
/// </remarks>
[ExcludeFromCodeCoverage]
internal abstract class TimeProvider
{
    /// <summary>
    /// Gets a <see cref="TimeProvider"/> that provides a clock based on <see cref="DateTimeOffset.UtcNow"/>.
    /// </summary>
    public static TimeProvider System { get; } = new SystemTimeProvider();

    /// <summary>
    /// Gets the current UTC time.
    /// </summary>
    /// <returns>The current UTC time.</returns>
    public virtual DateTimeOffset GetUtcNow() => DateTimeOffset.UtcNow;

    /// <summary>
    /// Gets the local time zone.
    /// </summary>
    public virtual TimeZoneInfo LocalTimeZone => TimeZoneInfo.Local;

    /// <summary>
    /// Gets the amount of time elapsed since the system started.
    /// </summary>
    /// <returns>The elapsed time since the system started.</returns>
    public virtual long GetTimestamp() => Stopwatch.GetTimestamp();

    /// <summary>
    /// Gets the frequency of the timer as the number of ticks per second.
    /// </summary>
    public virtual long TimestampFrequency => Stopwatch.Frequency;

    /// <summary>
    /// Creates a timer that invokes a callback at specified intervals.
    /// </summary>
    /// <param name="callback">The callback to invoke.</param>
    /// <param name="state">The state to pass to the callback.</param>
    /// <param name="dueTime">The amount of time to delay before the callback is invoked.</param>
    /// <param name="period">The time interval between invocations of the callback.</param>
    /// <returns>A timer that can be used to control the scheduling.</returns>
    public virtual ITimer CreateTimer(TimerCallback callback, object? state, TimeSpan dueTime, TimeSpan period)
    {
        return new SystemTimer(callback, state, dueTime, period);
    }

    private sealed class SystemTimeProvider : TimeProvider
    {
    }

    private sealed class SystemTimer : ITimer
    {
        private readonly Timer _timer;

        public SystemTimer(TimerCallback callback, object? state, TimeSpan dueTime, TimeSpan period)
        {
            _timer = new Timer(callback, state, dueTime, period);
        }

        public bool Change(TimeSpan dueTime, TimeSpan period)
        {
            return _timer.Change(dueTime, period);
        }

        public void Dispose()
        {
            _timer.Dispose();
        }

#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        public ValueTask DisposeAsync()
        {
            _timer.Dispose();
            return default;
        }
#endif
    }
}

/// <summary>
/// Represents a timer that can be changed or disposed.
/// </summary>
internal interface ITimer : IDisposable
#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
    , IAsyncDisposable
#endif
{
    /// <summary>
    /// Changes the start time and the interval between method invocations for a timer.
    /// </summary>
    /// <param name="dueTime">The amount of time to delay before the callback is invoked.</param>
    /// <param name="period">The time interval between invocations of the callback.</param>
    /// <returns>true if the timer was successfully updated; otherwise, false.</returns>
    bool Change(TimeSpan dueTime, TimeSpan period);
}

#endif
