using ANcpLua.Analyzers.DiscriminatedUnion.Extraction;
using ANcpLua.Analyzers.DiscriminatedUnion.Generation;

namespace ANcpLua.Analyzers.DiscriminatedUnion;

/// <summary>
///     Turns a <c>[DiscriminatedUnion]</c>-marked partial record root and its nested partial record
///     cases into a closed F#-style discriminated union: a <c>private</c> parameterless base
///     constructor (lock to nested cases), <c>sealed</c> case records derived from the root, and
///     exhaustive <c>Match&lt;TResult&gt;</c> / <c>Switch</c> dispatchers that the compiler enforces
///     to handle every case.
/// </summary>
/// <remarks>
///     Usage: declare the union root as <c>partial record</c> with one or more nested
///     <c>partial record</c> cases and apply <c>[DiscriminatedUnion]</c>. The generator emits the
///     base constructor, sealed inheritance, and dispatchers into a separate partial declaration.
///     The marker attribute itself is emitted via
///     <see cref="IncrementalGeneratorPostInitializationContext.AddSource(string, string)" /> so
///     consumers do not need a separate attribute package.
/// </remarks>
[Generator]
public sealed class DiscriminatedUnionGenerator : IIncrementalGenerator
{
    internal const string AttributeNamespace = "ANcpLua.Analyzers.DiscriminatedUnion";
    internal const string AttributeShortName = "DiscriminatedUnionAttribute";
    internal const string AttributeFullName = AttributeNamespace + "." + AttributeShortName;

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace ANcpLua.Analyzers.DiscriminatedUnion;

        /// <summary>
        /// Marks a partial record as the root of a closed discriminated union. Each nested
        /// <c>partial record</c> declared inside the marked type becomes a sealed case derived from
        /// the root. The generator emits a private parameterless base constructor that locks
        /// inheritance to the nested cases, plus exhaustive <c>Match&lt;TResult&gt;</c> and
        /// <c>Switch</c> dispatchers.
        /// </summary>
        /// <remarks>
        /// The decorated type must be declared <c>partial record</c> and must not declare a primary
        /// constructor. Cases must be declared as <c>partial record</c> directly nested inside the
        /// root.
        /// </remarks>
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Class,
            AllowMultiple = false,
            Inherited = false)]
        [global::System.Diagnostics.Conditional("ANCPLUA_DISCRIMINATED_UNION_USAGES")]
        internal sealed class DiscriminatedUnionAttribute : global::System.Attribute
        {
        }

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("DiscriminatedUnionAttribute.g.cs", AttributeSource));

        var flows = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, _) => node is RecordDeclarationSyntax,
            static (ctx, ct) => UnionExtractor.Extract(ctx, ct));

        var models = flows.ReportAndStop(context);

        var files = models
            .Select(static (model, _) => UnionOutputGenerator.Generate(model))
            .CollectAsEquatableArray();

        files.AddSources(context);
    }
}
