namespace ANcpLua.AotReflection;

internal static class OutputGenerator
{
    public static FileWithName GenerateOutput(TypeModel type)
    {
        var sb = new IndentedStringBuilder();
        sb.Append(GeneratedCodeHelpers.AutoGeneratedHeader("ANcpLua.AotReflection"));
        sb.AppendLine(GeneratedCodeHelpers.NullableEnable);
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(type.Namespace))
        {
            sb.AppendLine($"namespace {type.Namespace};");
            sb.AppendLine();
        }

        var blocks = 0;
        foreach (var declaration in type.DeclarationChain)
        {
            sb.AppendLine($"{declaration.Modifiers} {declaration.Keyword} {declaration.Name}{declaration.TypeParameters}");
            foreach (var clause in declaration.ConstraintClauses)
                sb.AppendLine(clause);

            sb.BeginBlock();
            blocks++;
        }

        ClassMetadataGenerator.WriteClassMetadata(sb, type);
        sb.AppendLine();
        ClassMetadataGenerator.WriteConvenienceMethods(sb, type);

        for (var i = 0; i < blocks; i++)
            sb.EndBlock();

        return new FileWithName(GetHintName(type), sb.ToString());
    }

    private static string GetHintName(TypeModel type)
    {
        var typeName = string.Join("+", type.DeclarationChain.Select(declaration => declaration.Name));
        return string.IsNullOrWhiteSpace(type.Namespace)
            ? $"{typeName}.AotReflection.g.cs"
            : $"{type.Namespace}.{typeName}.AotReflection.g.cs";
    }
}
